# Generated by Django 6.0.3 on 2026-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('moisture', models.FloatField()),
            ],
        ),
    ]
