name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          cd ~/crop-recommendation-ml

          git pull origin main

          docker stop crop-container || true
          docker rm crop-container || true

          docker build -t crop-project .

          docker run -d -p 8000:8000 --name crop-container crop-project
